import { Button, Divider } from "antd";
import arrow from "../../assets/images/shaded-arrow.svg";

const TabDDxList = () => {
  return (
    <div style={{ padding: "24px 0" }}>
      <div
        style={{
          display: "flex",
          alignContent: "center",
          flexDirection: "column",
          rowGap: "24px",
          padding: "0 10px",
        }}
      >
        <div
          style={{
            fontSize: 24,
            fontWeight: 600,
            lineHeight: "32px",
            textAlign: "center",
          }}
        >
          Differential Diagnosis
        </div>
        <span style={{ lineHeight: "26px", textAlign: "center" }}>
          Enter key symptoms and patient history to generate a list of possible
          diagnoses and recommended tests for confirmation. Ensure accurate data
          for best results.
        </span>
      </div>
      <div style={{ padding: "0 8px", marginTop: 16 }}>
        <Button
          type="primary"
          className="btn d-flex w-100 align-items-center justify-content-center btn-41"
        >
          <i className="icon-Add me-2 fs-21"></i>
          Generate DDx
        </Button>
      </div>
      <Divider />

      <div style={{ padding: "0px 12px" }}>
        <div
          className="d-flex align-items-center"
          style={{ paddingBottom: 10, columnGap: 8 }}
        >
          <div className="text-primary" style={{ fontWeight: 600 }}>
            Know More About DDx
          </div>
          <img src={arrow} alt="arrow" />
        </div>
        <div
          className="disclaimer-txt"
          style={{ color: "#A2A2A8", fontWeight: 600 }}
        >
          <b style={{ fontWeight: 700 }}>Disclaimer</b>: These results are
          generated by AI and should be used as a guide, not the final source
          for patient treatment decisions.
        </div>
      </div>
    </div>
  );
};

export default TabDDxList;
