import { Button, Collapse, Divider } from "antd";
import arrow from "../assets/images/shaded-arrow.svg";
import selectedTick from "../assets/images/tick.svg";
import ddxIcon from "../assets/images/ddxIcon.svg";
import loading from "../assets/images/loading.gif";
import genRxMic from "../assets/images/gen-rx-mic.svg";

import { useContext, useState } from "react";
// import CashManagerContext from "../../context/CashManagerContext";
import { useSelector } from "react-redux";
import { useLocation } from "react-router-dom";
import { getClinicName } from "../utils/utils";

const GenRxBox = ({
  handleDDxDrawer,
  handleDDxKnowMore,
  getGenerateDDx,
  handleDrawerVital,
}) => {
  //   const { diagnosisData, setDiagnosisData } = useContext(CashManagerContext);
  const { isDDxReadyToGenerate } = useSelector((state) => state.ddx);
  const { profile } = useSelector((state) => state.doctors);

  const { state } = useLocation();
  const { patient_data } = state;

  const [isCollapseActive, setIsCollapseActive] = useState(true);

  const handlePanelChange = () => {
    setIsCollapseActive((prev) => !prev);
  };

  const accordionItems = [
    {
      key: "1",
      label: (
        <div
          style={{
            borderRadius: "20px 20px 0 0",
          }}
          className="d-flex flex-column justify-content-between p-14"
        >
          <>
            <div className="d-flex align-items-center">
              <img
                src={genRxMic}
                alt="ddx-img"
                width={48}
                height={48}
                className="me-3"
              />
              <div
                className="title-common d-flex flex-column"
                style={{ gap: 4 }}
              >
                <span>Gen Rx</span>
              </div>
            </div>
            <button
              className="btn d-flex align-items-center btn-text"
              onClick={handleDrawerVital}
            />
            {isCollapseActive && (
              <div
                style={{
                  paddingTop: 10,
                }}
              >
                Quickly generate structured prescriptions by combining voice and
                type inputs, reducing time and effort in high-volume
                consultations
              </div>
            )}
          </>
        </div>
      ),
      children: (
        <div>
          <div
            className="d-flex flex-column justify-content-center align-items-center"
            style={{ gap: 10, paddingTop: "18px" }}
          >
            <Button
              className="btn btn-primary3 btn-41 px-4 w-100 d-flex align-items-center justify-content-center"
              style={{ gap: 10 }}
              onClick={() => getGenerateDDx("apexDDx")}
            >
              <img src={ddxIcon} alt="ddx-icon" />
              <span>Try Gen Rx</span>
            </Button>
          </div>
          <Divider />
          <div className="p-14" style={{ paddingTop: 0 }}>
            <div
              className="d-flex align-items-center"
              style={{
                paddingBottom: 10,
                columnGap: 8,
                cursor: "pointer",
                width: "fit-content",
              }}
              onClick={handleDDxKnowMore}
            >
              <div className="text-primary" style={{ fontWeight: 600 }}>
                Know More About Gen Rx
              </div>
              <img src={arrow} alt="arrow" />
            </div>
            <div
              className="disclaimer-txt"
              style={{
                color: "#A2A2A8",
                fontWeight: 500,
                fontSize: 12,
                paddingBottom: 20,
              }}
            >
              <b style={{ fontWeight: 700 }}>Disclaimer</b>: These results are
              generated by AI. Please double-check all details to ensure they
              are correct and complete.
            </div>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div>
      <div>
        <Collapse
          items={accordionItems}
          defaultActiveKey={["1"]}
          onChange={handlePanelChange}
          className="prescriptiontab-accordian cdss-collapse"
          expandIconPosition={"end"}
        />
      </div>
    </div>
  );
};

export default GenRxBox;
