export const customizationMockData = {
  _id: "68b828d7a9c90d9746de0b73",
  settings: {
    assessments: [
      {
        id: "basicInfo",
        title: "Basic Info",
        icon: "basicInfo",
        enabled: true,
        expanded: false,
        children: [
          {
            id: "chiefComplaint",
            title: "Chief Complaint",
            enabled: true,
            order: 2,
          },
          {
            id: "historyPresentIllness",
            title: "History of Present Illness",
            enabled: true,
            order: 1,
          },
          {
            id: "currentMedications",
            title: "Current Medications (Rx)",
            enabled: true,
            order: 3,
          },
          {
            id: "investigations",
            title: "Investigations",
            enabled: true,
            order: 4,
          },
          {
            id: "pastMedicalHistory",
            title: "Past Medical History",
            enabled: true,
            order: 5,
          },
          {
            id: "obstetricHistory",
            title: "Obstetric History",
            enabled: true,
            order: 6,
          },
          {
            id: "gyneacHistory",
            title: "Gynaec History",
            enabled: true,
            order: 7,
          },
        ],
      },
      {
        id: "physicalExamination",
        title: "Physical Examination",
        icon: "physicalExamination",
        enabled: true,
        expanded: false,
        children: [
          {
            id: "vitals",
            title: "Vitals",
            enabled: true,
            order: 1,
          },
          {
            id: "examinations",
            title: "Examinations",
            enabled: true,
            order: 2,
          },
          {
            id: "others",
            title: "Others",
            enabled: true,
            order: 3,
          },
          {
            id: "provisionalDiagnosis",
            title: "Provisional Diagnosis",
            enabled: true,
            order: 4,
          },
        ],
      },
      {
        id: "functionalAssessment",
        title: "Functional Assessment",
        icon: "functionalAssessment",
        enabled: true,
        expanded: false,
        children: [
          {
            id: "bedActivity",
            title: "Bed Activity",
            enabled: true,
            order: 1,
          },
          {
            id: "sitting",
            title: "Sitting",
            enabled: true,
            order: 2,
          },
          {
            id: "standing",
            title: "Standing",
            enabled: true,
            order: 3,
          },
          {
            id: "ambulation",
            title: "Ambulation",
            enabled: true,
            order: 4,
          },
          {
            id: "stairClimbing",
            title: "Stair Climbing",
            enabled: true,
            order: 5,
          },
          {
            id: "bedSoreOnAdmission",
            title: "Bed Sore on Admission",
            enabled: true,
            order: 6,
          },
          {
            id: "others",
            title: "Others",
            enabled: true,
            order: 7,
          },
          {
            id: "referredToPhysiotherapy",
            title: "Referred To Physiotherapy for Review",
            enabled: true,
            order: 8,
          },
        ],
      },
      {
        id: "treatmentPlan",
        title: "Treatment Plan",
        icon: "treatmentPlan",
        enabled: true,
        expanded: false,
        children: [
          {
            id: "immediateManagement",
            title: "Immediate Management",
            enabled: true,
            order: 1,
          },
          {
            id: "monitoringPlan",
            title: "Monitoring Plan",
            enabled: true,
            order: 2,
          },
        ],
      },
      {
        id: "additionalNotes",
        title: "Additional Notes",
        icon: "additionalNotes",
        enabled: true,
        expanded: false,
        children: [
          {
            id: "specialInstructions",
            title: "Special Instructions",
            enabled: true,
            order: 1,
          },
          {
            id: "dischargeCriteria",
            title: "Discharge Criteria",
            enabled: true,
            order: 2,
          },
        ],
      },
    ],
    progressNotes: [
      {
        id: "chiefComplaint",
        title: "Chief Complaint",
        icon: "chiefComplaint",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "findings",
        title: "Findings",
        icon: "findings",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "vitals",
        title: "Vitals",
        icon: "vitals",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "additionalRemarks",
        title: "Additional Remarks",
        icon: "additionalRemarks",
        enabled: true,
        expanded: false,
        children: [],
      },
    ],
    consultationNotes: [
      {
        id: "clinicalAssessmentPlan",
        title: "Clinical Assessment Plan",
        icon: "clinicalAssessmentPlan",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "vitals",
        title: "Vitals",
        icon: "vitals",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "medication",
        title: "Medication",
        icon: "medication",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "labInvestigation",
        title: "Lab Investigation",
        icon: "labInvestigation",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "additionalRemarks",
        title: "Additional Remarks",
        icon: "additionalRemarks",
        enabled: true,
        expanded: false,
        children: [],
      },
    ],
    otNotes: [
      {
        id: "surgeryDetails",
        title: "Surgery Details",
        icon: "surgeryDetails",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "surgeryTeam",
        title: "Surgery Team",
        icon: "surgeryTeam",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "operativeNotes",
        title: "Operative Notes",
        icon: "operativeNotes",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "intraOperativeNotes",
        title: "Intra Operative Notes",
        icon: "intraOperativeNotes",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "postOperativeNotes",
        title: "Post Operative Notes",
        icon: "postOperativeNotes",
        enabled: true,
        expanded: false,
        children: [],
      },
    ],
    crossReferral: [
      {
        id: "referralInformation",
        title: "Referral Information",
        icon: "referralInformation",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "consultantNotes",
        title: "Consultant Notes",
        icon: "consultantNotes",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "impression",
        title: "Impression",
        icon: "impression",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "additionalRemarks",
        title: "Additional Notes",
        icon: "additionalRemarks",
        enabled: true,
        expanded: false,
        children: [],
      },
      {
        id: "followUp",
        title: "Follow Up",
        icon: "followUp",
        enabled: true,
        expanded: false,
        children: [],
      },
    ],
  },
  doctorId: 524,
  hospitalId: 390,
  createdBy: 524,
  createdAt: "2025-09-03T11:39:03.739Z",
  updatedBy: 524,
  updatedAt: "2025-09-03T11:40:06.328Z",
};
