const dev = {
  appointment_api_url: `https://node-doctor.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  symptoms_api_url: `https://strauss-symptoms.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  examination_api_url: `https://strauss-examination.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  diagnosis_api_url: `https://strauss-diagnosis.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  advice_api_url: `https://strauss-advice.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  investigation_api_url: `https://strauss-investigation.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  medication_api_url: `https://strauss-medicine.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  vitals_api_url: `https://strauss-vital.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  casemanager_api_url: `https://strauss-casemanager.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  printsettings_api_url: `https://strauss-printsettings.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  medicalhistory_api_url: `https://strauss-medicalhistory.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  videolibrary_api_url: `https://strauss-videolibrary.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  sso_to_pm_url: `https://pms-upgrade.azurewebsites.net/api/get_doctor_sso_token.php`,
  sso_to_pm_admin_url: `https://pms-upgrade.azurewebsites.net/api/get_doctor_admin_sso_token.php`,
  sso_to_pm_username: `PM_40d30f01184aedc47`,
  sso_to_pm_password: `487154d8-b9ad-4314-a0e3-a72d5se84x14`,
  doctor_website_url: `https://pms-upgrade.azurewebsites.net/doctor_website/`,
  vaccination_api_url: `https://pm-vaccination-uat.mytatva.in/`,
  GROWTHBOOK_CLIENTKEY: "sdk-8jXEPwxajRuwkiyD",
  growth_chart_api_url: `https://pm-uat-growth-chart.tatvacare.in`,
  firebaseApiKey: "AIzaSyAfD-YLOjDLbhC7hwyiumSkNxP2lul_Kc0",
  firebaseAuthDomain: "diginext-28149.firebaseapp.com",
  firebaseDatabaseURL: "https://tc-care-default-rtdb.firebaseio.com",
  firebaseProjectId: "diginext-28149",
  firebaseStorageBucket: "diginext-28149.appspot.com",
  firebaseMessagingSenderId: "482265957598",
  firebaseAppId: "1:482265957598:web:5ecc05efdbed5c63f42e4f",
  tatvaRedirect: "https://diginextdoctor72093uat.azureedge.net/#/content?auto",
  gynec_api_url: "https://pm-medicalhistory-uat.tatvacare.in/api/v1/gynec-history",
  obstetric_api_url: "https://pm-medicalhistory-uat.tatvacare.in/api/v1/obstetric-history",
  zydus_api_url: `https://pm-ingest-webhook-uat.tatvacare.in`,
  zydus_business_id: '754811713438773',
  rx_digitization: "https://pm-rxdigitization-uat.tatvacare.in",
  visit_api_url: "https://pm-visit-integration-uat.tatvacare.in",
  lab_params_api_url: "https://pm-patient-docs-uat.tatvacare.in",
  opd_encryption_url:"https://api-uat.mytatva.in/api/v8/helper/encrypt_visit_data",
  upload_doc_api_url: "https://pm-patient-docs-uat.tatvacare.in/"
};

const qa = {
  appointment_api_url: `https://node-doctor.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  symptoms_api_url: `https://strauss-symptoms.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  examination_api_url: `https://strauss-examination.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  diagnosis_api_url: `https://strauss-diagnosis.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  advice_api_url: `https://strauss-advice.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  investigation_api_url: `https://strauss-investigation.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  medication_api_url: `https://strauss-medicine.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  vitals_api_url: `https://strauss-vital.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  casemanager_api_url: `https://strauss-casemanager.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  printsettings_api_url: `https://strauss-printsettings.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  medicalhistory_api_url: `https://strauss-medicalhistory.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  videolibrary_api_url: `https://strauss-videolibrary.salmonstone-47e08067.centralindia.azurecontainerapps.io`,
  sso_to_pm_url: `https://pms-upgrade.azurewebsites.net/api/get_doctor_sso_token.php`,
  sso_to_pm_admin_url: `https://pms-upgrade.azurewebsites.net/api/get_doctor_admin_sso_token.php`,
  sso_to_pm_username: `PM_40d30f01184aedc47`,
  sso_to_pm_password: `487154d8-b9ad-4314-a0e3-a72d5se84x14`,
  doctor_website_url: `https://pms-upgrade.azurewebsites.net/doctor_website/`,
  vaccination_api_url: `https://pm-vaccination-uat.mytatva.in/`,
  GROWTHBOOK_CLIENTKEY: "sdk-8jXEPwxajRuwkiyD",
  growth_chart_api_url: `https://pm-uat-growth-chart.tatvacare.in`,
  firebaseApiKey: "AIzaSyAfD-YLOjDLbhC7hwyiumSkNxP2lul_Kc0",
  firebaseAuthDomain: "diginext-28149.firebaseapp.com",
  firebaseDatabaseURL: "https://tc-care-default-rtdb.firebaseio.com",
  firebaseProjectId: "diginext-28149",
  firebaseStorageBucket: "diginext-28149.appspot.com",
  firebaseMessagingSenderId: "482265957598",
  firebaseAppId: "1:482265957598:web:5ecc05efdbed5c63f42e4f",
  tatvaRedirect: "https://diginextdoctor72093uat.azureedge.net/#/content?auto",
  gynec_api_url: "https://pm-medicalhistory-uat.tatvacare.in/api/v1/gynec-history",
  obstetric_api_url: "https://pm-medicalhistory-uat.tatvacare.in/api/v1/obstetric-history",
  zydus_api_url: `https://pm-ingest-webhook-uat.tatvacare.in`,
  zydus_business_id: '754811713438773',
  rx_digitization: "https://pm-rxdigitization-uat.tatvacare.in",
  visit_api_url: "https://pm-visit-integration-uat.tatvacare.in",
  lab_params_api_url: "https://pm-patient-docs-uat.tatvacare.in",
  opd_encryption_url:"https://api-uat.mytatva.in/api/v8/helper/encrypt_visit_data",
  upload_doc_api_url: "https://pm-patient-docs-uat.tatvacare.in/"
};

const uat = {
  appointment_api_url: `https://pm-master-uat-webservice.tatvacare.in`,
  symptoms_api_url: `https://pm-symptoms-uat.tatvacare.in`,
  examination_api_url: `https://pm-examination-uat.tatvacare.in`,
  diagnosis_api_url: `https://pm-diagnosis-uat.tatvacare.in`,
  advice_api_url: `https://pm-advice-uat.tatvacare.in`,
  investigation_api_url: `https://pm-investigation-uat.tatvacare.in`,
  medication_api_url: `https://pm-medicine-uat.tatvacare.in/`,
  vitals_api_url: `https://pm-vital-uat.tatvacare.in`,
  casemanager_api_url: `https://pm-casemanager-uat.tatvacare.in`,
  printsettings_api_url: `https://pm-printsetting-uat.tatvacare.in`,
  medicalhistory_api_url: `https://pm-medicalhistory-uat.tatvacare.in`,
  videolibrary_api_url: `https://pm-videolibrary-uat.tatvacare.in`,
  sso_to_pm_url: `https://pm-uat-dhspl-2.tatvacare.in/api/get_doctor_sso_token.php`,
  sso_to_pm_admin_url: `https://pm-uat-dhspl-2.tatvacare.in/api/get_doctor_admin_sso_token.php`,
  sso_to_pm_username: `PM_40d30f01184aedc47`,
  sso_to_pm_password: `487154d8-b9ad-4314-a0e3-a72d5se84x14`,
  doctor_website_url: `https://pm-uat-dhspl-2.tatvacare.in/doctor_website/`,
  vaccination_api_url: `https://pm-vaccination-uat.mytatva.in/`,
  GROWTHBOOK_CLIENTKEY: "sdk-8jXEPwxajRuwkiyD",
  growth_chart_api_url: `https://pm-uat-growth-chart.tatvacare.in`,
  firebaseApiKey: "AIzaSyAfD-YLOjDLbhC7hwyiumSkNxP2lul_Kc0",
  firebaseAuthDomain: "diginext-28149.firebaseapp.com",
  firebaseDatabaseURL: "https://tc-care-default-rtdb.firebaseio.com",
  firebaseProjectId: "diginext-28149",
  firebaseStorageBucket: "diginext-28149.appspot.com",
  firebaseMessagingSenderId: "482265957598",
  firebaseAppId: "1:482265957598:web:5ecc05efdbed5c63f42e4f",
  tatvaRedirect: "https://doctor-uat.tatvacare.in#bypass_pedia=false",
  gynec_api_url: "https://pm-medicalhistory-uat.tatvacare.in/api/v1/gynec-history",
  obstetric_api_url: "https://pm-medicalhistory-uat.tatvacare.in/api/v1/obstetric-history",
  zydus_api_url: `https://pm-ingest-webhook-uat.tatvacare.in`,
  zydus_business_id: '754811713438773',
  rx_digitization: "https://pm-rxdigitization-uat.tatvacare.in",
  visit_api_url: "https://pm-visit-integration-uat.tatvacare.in",
  lab_params_api_url: "https://pm-patient-docs-uat.tatvacare.in",
  opd_encryption_url:"https://api-uat.mytatva.in/api/v8/helper/encrypt_visit_data",
  upload_doc_api_url: "https://pm-patient-docs-uat.tatvacare.in/"
};

const prod = {
  appointment_api_url: `https://pm-master-prod-webservice.tatvacare.in`,
  symptoms_api_url: `https://pm-symptoms-prod.tatvacare.in`,
  examination_api_url: `https://pm-examination-prod.tatvacare.in`,
  diagnosis_api_url: `https://pm-diagnosis-prod.tatvacare.in`,
  advice_api_url: `https://pm-advice-prod.tatvacare.in`,
  investigation_api_url: `https://pm-investigation-prod.tatvacare.in`,
  medication_api_url: `https://pm-medicine-prod.tatvacare.in/`,
  vitals_api_url: `https://pm-vital-prod.tatvacare.in`,
  casemanager_api_url: `https://pm-casemanager-prod.tatvacare.in`,
  printsettings_api_url: `https://pm-printsetting-prod.tatvacare.in`,
  medicalhistory_api_url: `https://pm-medicalhistory-prod.tatvacare.in`,
  videolibrary_api_url: `https://pm-videolibrary-prod.tatvacare.in`,
  sso_to_pm_url: `https://practice.tatvacare.in/api/get_doctor_sso_token.php`,
  sso_to_pm_admin_url: `https://practice.tatvacare.in/api/get_doctor_admin_sso_token.php`,
  sso_to_pm_username: `PM_45dy48vh8sc4i1dum`,
  sso_to_pm_password: `481541at-j4xc-4817-q5xz-a4rt48c69bt1`,
  doctor_website_url: `https://practice.tatvacare.in/doctor_website/`,
  vaccination_api_url: `https://pm-vaccination-prod.tatvacare.in/`,
  GROWTHBOOK_CLIENTKEY: "sdk-qAxUqghZDXqcMH45",
  firebaseApiKey: "AIzaSyDijmTNFqGW8047ELts2cztM88mibYrjvw",
  firebaseAuthDomain: "tatvacare.firebaseapp.com",
  firebaseDatabaseURL: "https://tatvacare.firebaseio.com",
  firebaseProjectId: "tatvacare",
  firebaseStorageBucket: "tatvacare.appspot.com",
  firebaseMessagingSenderId: "601922359186",
  firebaseAppId: "1:601922359186:web:a3b9df05589faed1f5fb4b",
  growth_chart_api_url: `https://pm-prod-growth-chart.tatvacare.in`,
  tatvaRedirect: "https://diginextloginprod.z10.web.core.windows.net/login/index.html#bypass_pedia=false",
  gynec_api_url: "https://pm-medicalhistory-prod.tatvacare.in/api/v1/gynec-history",
  obstetric_api_url: "https://pm-medicalhistory-prod.tatvacare.in/api/v1/obstetric-history",
  zydus_api_url: `https://pm-ingest-webhook-prod.tatvacare.in`,
  zydus_business_id: '368451724046474',
  rx_digitization: "https://pm-rxdigitization-uat.tatvacare.in",
  visit_api_url: "https://pm-visit-integration-prod.tatvacare.in",
  lab_params_api_url: "https://pm-patient-docs-uat.tatvacare.in",
  opd_encryption_url:"https://api-uat.mytatva.in/api/v8/helper/encrypt_visit_data",
  upload_doc_api_url: "https://pm-patient-docs-prod.tatvacare.in/"
};

const getEnv = () => {
  switch (process.env.REACT_APP_ENV) {
    case "dev":
      return uat;
    case "qa":
      return qa;
    case "uat":
      return uat;
    case "prod":
      return prod;
    default:
      break;
  }
};
export const env = getEnv();
