name: Trigger auto deployment for pm-doctor-portal-ipd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ ipd-dev ]
    paths:
    - '**'
    - '.github/workflows/pm-doctor-portal-ipd-AutoDeployTrigger-834f0c67-22fa-4a4f-b20a-309cbd13e0ec.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PMDOCTORPORTALIPD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PMDOCTORPORTALIPD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PMDOCTORPORTALIPD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: practiceqa.azurecr.io
          registryUsername: ${{ secrets.PMDOCTORPORTALIPD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PMDOCTORPORTALIPD_REGISTRY_PASSWORD }}
          containerAppName: pm-doctor-portal-ipd
          resourceGroup: tatva-uat
          imageToBuild: practiceqa.azurecr.io/pm-doctor-portal-ipd:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


