name: Trigger auto deployment for pm-doctor-portal-ipd-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ ipd-prod ]
    paths:
    - '**'
    - '.github/workflows/pm-doctor-portal-ipd-prod-AutoDeployTrigger-43a3c61d-0e90-4ef7-8ded-7d2d13d65ce0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PMDOCTORPORTALIPDPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PMDOCTORPORTALIPDPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PMDOCTORPORTALIPDPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: mytatvaprodcr.azurecr.io
          registryUsername: ${{ secrets.PMDOCTORPORTALIPDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PMDOCTORPORTALIPDPROD_REGISTRY_PASSWORD }}
          containerAppName: pm-doctor-portal-ipd-prod
          resourceGroup: tatva-prod
          imageToBuild: mytatvaprodcr.azurecr.io/pm-doctor-portal-ipd-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


