# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - uat-doctor-portal

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      REACT_APP_ENV: uat

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acinacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_65ca567e6c3148aca34395cbe1137321 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ea998d487c5a49cfb61ba506ca9df111 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acinacr.azurecr.io/doctor-portal/uat:${{ github.sha }}
        file: ./Dockerfile
        build-args: REACT_APP_ENV=${{ env.REACT_APP_ENV }}  # Pass REACT_APP_ENV as a build argument

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'uat-doctor-portal'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af9c474eee78453ab1288f797f770f14 }}
        images: 'acinacr.azurecr.io/doctor-portal/uat:${{ github.sha }}'