name: Trigger auto deployment for zy-doctor-portal-ipd-prod

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENV: zy-prod

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ZYDOCTORPORTALIPDPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ZYDOCTORPORTALIPDPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ZYDOCTORPORTALIPDPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: zypractice04.azurecr.io
          registryUsername: ${{ secrets.ZYDOCTORPORTALIPDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ZYDOCTORPORTALIPDPROD_REGISTRY_PASSWORD }}
          containerAppName: zy-doctor-portal-ipd-prod
          resourceGroup: practice-prod
          imageToBuild: zypractice04.azurecr.io/zy-doctor-portal-ipd-prod:${{ github.sha }}
          buildArguments: |
            REACT_APP_ENV=zy-prod
